In [1]:
import numpy as np

In [4]:
a = [i for i in range(10)]

In [6]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [7]:
b = np.array(a)

In [8]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
type(b)

numpy.ndarray

In [10]:
b = np.array(a, dtype = float)

In [11]:
type(b)

numpy.ndarray

In [12]:
b[1]

1.0

In [13]:
b = np.array(a, dtype = int)

In [14]:
b[0 ]

0

In [15]:
b.ndim

1

In [16]:
b.shape

(10,)

In [20]:
b = np.array([[i for i in range(10)],[i for i in range(10)],[i for i in range(10)]])

In [21]:
b.shape 

(3, 10)

In [22]:
b.ndim

2

In [23]:
b.size

30

In [24]:
b[1][2]

2

In [25]:
b[2, 5]

5

In [26]:
b[0:2, 0:3]

array([[0, 1, 2],
       [0, 1, 2]])

In [28]:
b[1:, 5:]

array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])

In [30]:
c = b[1:,5:]

In [31]:
c

array([[5, 6, 7, 8, 9],
       [5, 6, 7, 8, 9]])

In [32]:
c = b[1:, 5: ].copy()

In [33]:
b = np.array([1., 2., 3.], dtype = np.float32)

In [34]:
b

array([1., 2., 3.], dtype=float32)

In [35]:
d = np.array([1., 3., 5.], dtype = np.float64)

In [36]:
d

array([1., 3., 5.])

In [37]:
d.dtype

dtype('float64')

In [39]:
e = np.array([1,2,4], dtype = np.int64)

In [40]:
e

array([1, 2, 4])

In [41]:
e.dtype 

dtype('int64')

In [42]:
f = np.array([1,2,3] , dtype = np.int32)

In [43]:
f

array([1, 2, 3], dtype=int32)