# Применение numpy для линейной алгебры

In [1]:
import numpy as np

Умножение матриц 

In [2]:
X1 = np.array([[1,2],[3,4],[5,6]])

In [3]:
X2 = np.array([[7,8,9,10],
              [11,12,13, 14]])


In [4]:
X1.shape 

(3, 2)

In [5]:
X2.shape

(2, 4)

Число стобцов первой матрица должно равняться числу срок второй матрицы:

In [7]:
X1.shape[1] == X2.shape[0]

True

In [8]:
Z = np.dot(X1, X2)
Z

array([[ 29,  32,  35,  38],
       [ 65,  72,  79,  86],
       [101, 112, 123, 134]])

In [9]:
Z.shape

(3, 4)

Как получен элемент матрица Z нулевой строки и нулевого столбца:



In [11]:
X1[0,0] * X2[0,0] + X1[0,1] * X2[1,0]

29

Как получен элемент матрица Z нулевой строки и первого столбца:

In [12]:
X1[0,0] * X2[0,1] + X1[0,1] * X2[1,1]

32

Модуль numpy.linalg: возведение матрицы в квадрат

In [21]:
A = np.array([[0,1,2],
             [3,4,5],
             [6,7,8]])

In [15]:
A_square = np.dot(A,A)
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

In [17]:
A_square = np.linalg.matrix_power(A,2)
A_square

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

### Создание единичной матрицы

Единичная матрица - квадратная матрица с единицами по главной диагонали и нулями в остальных ячейках

In [18]:
I = np.eye(3)

In [19]:
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Умножение матрицы на единичную матрицу


In [22]:
np.dot(I, A)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [23]:
np.dot(A, I)

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

### Транспонирование матрицы 

In [29]:
A = np.array([[11,13], 
             [16, 9],
             [8,15]])


In [30]:
At = A.transpose()
At

array([[11, 16,  8],
       [13,  9, 15]])

Альтернативный вариант

In [31]:
At  = A.T
At

array([[11, 16,  8],
       [13,  9, 15]])

Рассмотрим матрицы X и Y

In [33]:
X = np.array([[1,2],[3,4],[5,6]])

In [35]:
Y = np.array([[0,1],[3,4],[5,6],[6,7]])

In [38]:
Yt = Y.T

In [39]:
Yt

array([[0, 3, 5, 6],
       [1, 4, 6, 7]])

### Вычислние определителя и ранга матрицы 

Пример 1 

In [45]:
Aq = np.array([[0,1,2],[3,4,5],[6,7,8]])

In [46]:
np.linalg.det(Aq)

0.0

In [47]:
np.linalg.matrix_rank(A)

2

In [48]:
Bq = np.array([[7,4,5],[8,3,2,],[6,10,12]])

In [49]:
np.linalg.det(Bq)

85.99999999999997

In [50]:
np.linalg.matrix_rank(Bq)

3

Пример 3 (можно узнать только ранг матрицы, но не определитель, так как она не квадратная)

In [52]:
Cq = np.array([[1,2],[3,4],[5,6]])

In [54]:
np.linalg.matrix_rank(Cq)

2

In [55]:
Dq = np.array([[7,4,5],[8,3,2],[6,10,12]])

In [56]:
B_inv = np.linalg.inv(Dq)
B_inv

array([[ 0.18604651,  0.02325581, -0.08139535],
       [-0.97674419,  0.62790698,  0.30232558],
       [ 0.72093023, -0.53488372, -0.12790698]])