In [1]:
import numpy as np

Автоматическое создание массивов

In [2]:
a = np.zeros((3,4))

In [3]:
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
a = np.ones((5,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

В обратном порядке

In [10]:
np.arange(0,10,-2)

array([], dtype=int64)

In [11]:
np.arange(10, 0 , -2)

array([10,  8,  6,  4,  2])

In [12]:
np.linspace(0, 9.9,100)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [13]:
np.logspace(0,3,4)

array([   1.,   10.,  100., 1000.])

Генерация случайных чисел

In [14]:
np.random.sample()

0.4000880719380703

In [15]:
np.random.sample(3)

array([0.36195952, 0.86988129, 0.41872252])

In [16]:
np.random.sample((3,4))

array([[0.65620594, 0.66090566, 0.55978385, 0.05068504],
       [0.43869795, 0.82734463, 0.29249275, 0.8134367 ],
       [0.69492147, 0.26227932, 0.31062872, 0.78136704]])

In [18]:
np.random.sample((64, 32 , 3))

array([[[2.35844039e-01, 3.13103491e-01, 5.32079959e-01],
        [5.21284130e-01, 1.12448726e-02, 8.23429936e-01],
        [8.41065381e-01, 3.76724516e-01, 4.22285451e-02],
        ...,
        [5.70020278e-01, 4.61518707e-01, 1.17775576e-01],
        [7.18973118e-01, 4.51580298e-01, 2.18842047e-01],
        [6.38102275e-02, 5.26626269e-01, 8.82711709e-01]],

       [[2.47803246e-02, 5.56749291e-01, 4.02919862e-01],
        [6.78151065e-01, 4.03172507e-01, 1.40722715e-01],
        [1.72451154e-01, 2.57592771e-01, 1.75612709e-01],
        ...,
        [1.44044667e-01, 9.27020058e-01, 3.57496002e-01],
        [9.61317609e-02, 2.67056515e-01, 3.18074898e-01],
        [4.01955061e-01, 8.54071881e-01, 4.74264376e-01]],

       [[2.94681834e-01, 5.46669870e-01, 5.06601342e-01],
        [3.66583391e-01, 8.62065481e-01, 2.65314828e-03],
        [1.38166042e-01, 9.49442854e-01, 2.68857739e-01],
        ...,
        [6.68453831e-01, 6.52574539e-01, 8.64041121e-01],
        [8.81872000e-01, 6.96

In [19]:
np.random.randn(3,4)

array([[ 0.6232398 ,  1.74222916, -0.49794311, -0.26683649],
       [-1.15561053, -0.10463178,  1.23828944, -1.57677956],
       [-0.56830588, -1.27701195,  0.46600132, -0.2271449 ]])

In [20]:
np.random.randint(0,100,10)

array([53, 39, 41, 18,  5, 31, 93, 57, 64, 66])

In [21]:
np.random.randint(0,10,(3,4))

array([[4, 4, 0, 1],
       [0, 9, 5, 2],
       [2, 4, 1, 4]])

numpy.random.choise -случайный выбор элемента из массива

In [27]:
b = np.array([0.42264034, 0.22967136, 0.49131777])
b

array([0.42264034, 0.22967136, 0.49131777])

In [29]:
np.random.choice(b)

0.22967136

In [30]:
np.random.choice(b,3)

array([0.42264034, 0.22967136, 0.22967136])

In [32]:
np.random.seed(42)

In [33]:
np.random.randint(0, 10 , 3)

array([6, 3, 7])

Изменение формы массива

In [38]:
r = np.arange(12)
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [39]:
r.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [40]:
np.reshape(a, (3, -1))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
np.reshape(r,(-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [43]:
r.resize(3,4)
r

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Соединение массивов

Для наглядности возьмем два массива 

In [45]:
a2 = np.random.sample((3,3))
a3 = np.random.sample((3,3))
a2,a3

(array([[0.13949386, 0.29214465, 0.36636184],
        [0.45606998, 0.78517596, 0.19967378],
        [0.51423444, 0.59241457, 0.04645041]]),
 array([[0.60754485, 0.17052412, 0.06505159],
        [0.94888554, 0.96563203, 0.80839735],
        [0.30461377, 0.09767211, 0.68423303]]))

In [47]:
v = np.vstack((a2,a3))
v

array([[0.13949386, 0.29214465, 0.36636184],
       [0.45606998, 0.78517596, 0.19967378],
       [0.51423444, 0.59241457, 0.04645041],
       [0.60754485, 0.17052412, 0.06505159],
       [0.94888554, 0.96563203, 0.80839735],
       [0.30461377, 0.09767211, 0.68423303]])

In [48]:
np.concatenate((a2,a3), axis = 0)

array([[0.13949386, 0.29214465, 0.36636184],
       [0.45606998, 0.78517596, 0.19967378],
       [0.51423444, 0.59241457, 0.04645041],
       [0.60754485, 0.17052412, 0.06505159],
       [0.94888554, 0.96563203, 0.80839735],
       [0.30461377, 0.09767211, 0.68423303]])

Соединение в глубину (в третьем измерении)

In [50]:
d = np.dstack([a2,a3])

In [51]:
d

array([[[0.13949386, 0.60754485],
        [0.29214465, 0.17052412],
        [0.36636184, 0.06505159]],

       [[0.45606998, 0.94888554],
        [0.78517596, 0.96563203],
        [0.19967378, 0.80839735]],

       [[0.51423444, 0.30461377],
        [0.59241457, 0.09767211],
        [0.04645041, 0.68423303]]])